source 'https://rubygems.org'
ruby '2.1.1'

gem 'sinatra', '~> 1.4.4'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'activerecord-postgresql-adapter'
gem 'slim'
gem 'rack'
gem 'pry'
gem 'sinatra-env', '~> 0.0.2'
gem 'rake'