development:
  adapter: postgresql
  database: flufy_db
  username: flufyuser
  password: d4t4!flufy
  host: localhost
  port: 5432
production:
  adapter: postgresql
  database: flufy_db
  username: flufyuser
  password: d4t4!flufy