development:
  adapter: mysql2
  database: flufy_db
  username: flufyuser
  password: d4t4!flufy
  host: 127.0.0.1
  port: 3306
production:
  adapter: mysql2
  database: flufy_db
  username: flufyuser
  password: d4t4!flufy
  host: 127.0.0.1
  port: 3306